<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thng tin khi to</name>
   <tag></tag>
   <elementGuidId>06a6ca53-c5c2-47dc-8b4a-abc49c4b318a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ng-star-inserted.nav-item > a.nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eff1b2a0-f25d-4388-bcd0-b7c1cd37f083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>93a17afc-628c-4f32-a42e-52f9b5a2356b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4a7f7b58-98a6-435c-a96c-1660d30370ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>f76869e0-9dd8-40d5-bbb2-c2ec2ab3f75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d13a2c2-914c-4816-8009-09acdceed414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin khởi tạo </value>
      <webElementGuid>684c5bf4-3cb6-493c-a33a-0e78672bf5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-valid&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/tabset[@id=&quot;property-tabs&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[@class=&quot;ng-star-inserted nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>b86231d3-1a58-454d-91ae-a94f0e71226e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='']</value>
      <webElementGuid>690f8d13-32fa-4f15-bd80-70638b629726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/ul/li/a</value>
      <webElementGuid>cd9fc6a8-34e7-4fd9-a0d1-41301c2460e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>cf57088f-cbc4-418d-abf2-27395b323e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tabset/ul/li/a</value>
      <webElementGuid>feca5411-c7f6-48e7-9c66-3e7ad96898ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Thông tin khởi tạo ' or . = 'Thông tin khởi tạo ')]</value>
      <webElementGuid>6b00fd07-ee47-4da3-820b-444264c16ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
