<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Yu cu cn x l</name>
   <tag></tag>
   <elementGuidId>17385cb1-3de7-4a27-9712-5bf680811b59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '/v2/request-list-approval/request-need-processing')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8783d7ce-5279-4fa4-a841-179049b282f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>3e2725e7-1cba-42ca-b009-deec7c5a62b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-preserve-fragment</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2972e02-117c-4f7e-a73d-ea5a60bffde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-skip-location-change</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>366e05ff-8069-4650-8fc1-2162fcfed23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-replace-url</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11300211-effa-434b-af38-4c9907bc64f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/request-list-approval/request</value>
      <webElementGuid>6c106efa-6531-47db-a87e-35294fc82b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>061852fc-9e23-4fc6-ac5a-3f85e38f0fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active-options</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9dcfd599-8dcb-49a6-89d4-c0c707bcc385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link ng-star-inserted</value>
      <webElementGuid>87775d1f-c444-455c-985f-508cf0127710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/v2/request-list-approval/request-need-processing</value>
      <webElementGuid>1c6e84fb-9765-4a48-b5dd-653ffe27f2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yêu cầu cần xử lý</value>
      <webElementGuid>78dc5ae1-f994-4b4c-ab34-2bc670e6ba4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed&quot;]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-body&quot;]/app-sidebar[@class=&quot;sidebar ng-star-inserted&quot;]/app-sidebar-nav[@class=&quot;ps sidebar-nav&quot;]/app-sidebar-nav-items[@class=&quot;nav&quot;]/app-sidebar-nav-dropdown[@class=&quot;open nav-item nav-dropdown child_0 _menu-child_0 ng-star-inserted&quot;]/app-sidebar-nav-items[@class=&quot;nav-dropdown-items&quot;]/app-sidebar-nav-link[@class=&quot;nav-item child_1 _menu-child_0,0 ng-star-inserted&quot;]/a[@class=&quot;nav-link ng-star-inserted&quot;]</value>
      <webElementGuid>a2013277-a4ca-41e0-8390-947745844ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/v2/request-list-approval/request-need-processing')]</value>
      <webElementGuid>90507e78-8ef5-48e5-9405-285cba6716cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-sidebar-nav-link/a</value>
      <webElementGuid>3e37e080-560c-4ff6-898c-3c4e08ff79b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/v2/request-list-approval/request-need-processing' and (text() = 'Yêu cầu cần xử lý' or . = 'Yêu cầu cần xử lý')]</value>
      <webElementGuid>901a7619-a28d-4616-b170-0136632115c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
