<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_To mi</name>
   <tag></tag>
   <elementGuidId>6ec86870-6c96-409c-a4e7-47ec0ee7066a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[33]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-center.mt-3 > button.btn.w-auto.btn-primary.create-profile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91c1d46c-25d4-4374-99bd-23cbccbf24a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99dc7fc9-602d-4614-ba75-cb9cdf57268b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn w-auto btn-primary create-profile</value>
      <webElementGuid>9733dbdd-74bd-40db-b742-c5a4d6bb5c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tạo mới   </value>
      <webElementGuid>de143026-91e6-49ad-ae60-b9f138bd7e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;ng-tns-c264-12 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c264-12 p-dialog-mask p-component-overlay p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c264-12 profile-customer-history-sbo p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c264-12&quot;]/ca-profile-customer-history[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mr-2 ml-2 profile-customer-history-sbo&quot;]/div[@class=&quot;text-center mt-3&quot;]/button[@class=&quot;btn w-auto btn-primary create-profile&quot;]</value>
      <webElementGuid>5a9bfc46-d7f3-47eb-b9b9-d65c647415fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[33]</value>
      <webElementGuid>a8504c69-a55b-4848-9622-e1a32c013fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[3]</value>
      <webElementGuid>9c280d09-c263-4e36-8ae0-958d7988a442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Tạo mới   ' or . = ' Tạo mới   ')]</value>
      <webElementGuid>b07fa7fb-f6c3-4945-80e9-be594fe55b5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
