<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thng tin khon vay</name>
   <tag></tag>
   <elementGuidId>18011246-6efa-4d8a-bc51-8c8067509d33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>761633fa-a954-4a91-8502-3dc840b55327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>799202ae-a2d2-4942-928b-e7709d7cb3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-tab pb-3 mr-3 ng-star-inserted</value>
      <webElementGuid>12d0b86a-38cf-4507-8934-b589788e1168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Thông tin khoản vay </value>
      <webElementGuid>b892046c-8dbc-46b2-a549-c1e8d5a7b360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-left&quot;)/div[@class=&quot;main-app-shell ng-star-inserted&quot;]/ca-rb-common-approval[@class=&quot;ng-star-inserted&quot;]/ca-rm-request-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;main-nav-tabs p-d-flex p-justify-between mt-3&quot;]/div[1]/button[@class=&quot;btn btn-tab pb-3 mr-3 ng-star-inserted&quot;]</value>
      <webElementGuid>98882e48-854b-48e0-b8f2-0f287af415f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>0846a8c0-25ac-4c0a-972d-98918527db9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//as-split-area[@id='main-left']/div/ca-rb-common-approval/ca-rm-request-detail/div/div/div/button[4]</value>
      <webElementGuid>d2b00f2f-f7b9-4519-b8a6-8755d7ea1097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[4]</value>
      <webElementGuid>1f1c1afa-9749-4716-b2eb-f0ee2fa5bdde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Thông tin khoản vay ' or . = ' Thông tin khoản vay ')]</value>
      <webElementGuid>aa462f88-be4e-4ec2-95cb-2bbf90e0f002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
