<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng</name>
   <tag></tag>
   <elementGuidId>1544eab9-faca-4eee-b982-55da9ac53c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[104]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7015fd8-5656-4dd0-a8d4-6ac2c1ea3328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7259a34e-4486-47e6-b81d-7e08cb157187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ng-star-inserted</value>
      <webElementGuid>2e100978-6b10-4dea-b18f-4b6d70356060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>btn-primary</value>
      <webElementGuid>681fa953-5d7c-4474-b3f9-d6c2702d76e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Đóng </value>
      <webElementGuid>84675e1f-b2cf-4aa4-b396-d73078845fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed bosbo p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;ng-tns-c313-143 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c313-143 p-dialog-mask p-component-overlay p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c313-143 p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c313-143&quot;]/ca-confirm-dialog[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;text-center mt-4&quot;]/button[@class=&quot;btn btn-primary ng-star-inserted&quot;]</value>
      <webElementGuid>7c2eaace-d32e-46ec-b250-4a69c346d0a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[104]</value>
      <webElementGuid>d090320e-5dc4-4206-86f8-280626a20854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ca-confirm-dialog/div[2]/button</value>
      <webElementGuid>d6435b07-737d-4e00-b5ba-7719df1632b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Đóng ' or . = ' Đóng ')]</value>
      <webElementGuid>71aedc05-3bb5-412d-b7d7-e8fc89f4cd5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
