<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lu</name>
   <tag></tag>
   <elementGuidId>b5103add-7c3d-4850-b48a-f997057babf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[99]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-fill-secondary.btn-done.approval_toolbar_action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df468ac4-2ea0-4839-b78b-9f6824172ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7599a680-bcc2-4da4-9480-3f80acf4a259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-fill-secondary btn-done approval_toolbar_action</value>
      <webElementGuid>3cef2128-d27d-42c0-8308-0cecbbabef6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lưu </value>
      <webElementGuid>76db7638-9dc7-4579-bf3b-71680cb9845c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-left&quot;)/div[@class=&quot;main-app-shell ng-star-inserted&quot;]/ca-rb-common-approval[@class=&quot;ng-star-inserted&quot;]/ca-rm-request-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;approval_toolbar ng-star-inserted&quot;]/button[@class=&quot;btn btn-fill-secondary btn-done approval_toolbar_action&quot;]</value>
      <webElementGuid>9ae95975-2440-47bc-9821-3e2431053f4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[99]</value>
      <webElementGuid>3fa726e2-047a-475b-87ba-fcb3b2a0d683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//as-split-area[@id='main-left']/div/ca-rb-common-approval/ca-rm-request-detail/div[2]/button</value>
      <webElementGuid>c7c2e72e-ff32-4dbb-8aa3-40c3638501d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>27758ddd-1d17-491a-8331-1d011c551e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Lưu ' or . = ' Lưu ')]</value>
      <webElementGuid>06da6a34-b113-4392-8c9c-b0b10f793b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
