<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HP</name>
   <tag></tag>
   <elementGuidId>ee664f74-b0ab-450d-bf1b-5078c62e0cd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab/ca-init-application-info/div/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[7]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/div[3]/div[2]/ul/p-dropdownitem/li/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.align-items-center.gap-2.label-custom.ng-star-inserted > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b55fdc3-d183-4b4a-9a1f-4c7d11bd8835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HP</value>
      <webElementGuid>0eb6b7c4-7be7-447c-b598-7ebc733c93b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active approval-tab-error&quot;]/ca-init-application-info[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/bpm-formly-form[1]/bpm-formly-field[1]/bpm-formly-group[@class=&quot;ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;ng-star-inserted&quot;]/bpm-formly-group[@class=&quot;row ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;col-md-6 ng-star-inserted&quot;]/ca-filter-status-dropdown[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;custom-form&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;p-inputgroup _input-left&quot;]/div[@class=&quot;input-group-prepend&quot;]/p-dropdown[@class=&quot;dropdown-custom ng-tns-c358-22 ng-untouched ng-pristine ng-star-inserted ng-invalid p-inputwrapper-focus&quot;]/div[@class=&quot;ng-tns-c358-22 p-dropdown p-component p-dropdown-open p-dropdown-clearable&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c358-22 panel-filter p-dropdown-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-items-wrapper ng-tns-c358-22&quot;]/ul[@class=&quot;p-dropdown-items ng-tns-c358-22&quot;]/p-dropdownitem[@class=&quot;ng-tns-c358-22 ng-star-inserted&quot;]/li[@class=&quot;p-dropdown-item p-ripple&quot;]/div[@class=&quot;flex align-items-center gap-2 label-custom ng-star-inserted&quot;]/div[1]</value>
      <webElementGuid>580e60d3-5f3b-4bd2-9f0a-e675f55c7a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab/ca-init-application-info/div/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[7]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/div[3]/div[2]/ul/p-dropdownitem/li/div/div</value>
      <webElementGuid>75202e3f-67a8-4098-9177-f46c79fabd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>b47ead70-dd7e-41c0-996b-33e21287125e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'HP' or . = 'HP')]</value>
      <webElementGuid>62b08a03-500f-4513-9e9c-4391dcaff1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
