<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cho thukhai thc ti sn</name>
   <tag></tag>
   <elementGuidId>0974f785-5246-4d1b-85d7-73ff3d590e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/div[2]/ca-actual-income/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[29]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/div[3]/div[2]/ul/p-dropdownitem[2]/li/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acf39adc-9b1f-47b6-9d2a-8882fc21432c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cho thuê/khai thác tài sản</value>
      <webElementGuid>5f3a2505-b1a1-489e-a050-7fb4b0f78a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-invalid&quot;]/form[@class=&quot;ng-touched ng-dirty ng-invalid&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active approval-tab-error&quot;]/ca-income-source-information[@class=&quot;ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;card card-border ng-star-inserted&quot;]/div[@class=&quot;bord rounded pb-4 mb-4 ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;collapse in show ng-star-inserted&quot;]/ca-actual-income[@class=&quot;ng-touched ng-dirty ng-invalid ng-star-inserted&quot;]/div[@class=&quot;bpm-dynamic-form&quot;]/bpm-formly-form[1]/bpm-formly-field[1]/bpm-formly-group[@class=&quot;ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;ng-star-inserted&quot;]/bpm-formly-group[@class=&quot;col-md-12 row ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;col-md-6 ng-star-inserted&quot;]/ca-filter-status-dropdown[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;custom-form&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-xl-8 col-md-7&quot;]/div[@class=&quot;p-inputgroup _input-left&quot;]/div[@class=&quot;input-group-prepend&quot;]/p-dropdown[@class=&quot;dropdown-custom ng-tns-c358-152 ng-untouched ng-pristine ng-invalid ng-star-inserted p-inputwrapper-focus&quot;]/div[@class=&quot;ng-tns-c358-152 p-dropdown p-component p-dropdown-open p-dropdown-clearable&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c358-152 panel-filter p-dropdown-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-items-wrapper ng-tns-c358-152&quot;]/ul[@class=&quot;p-dropdown-items ng-tns-c358-152&quot;]/p-dropdownitem[@class=&quot;ng-tns-c358-152 ng-star-inserted&quot;]/li[@class=&quot;p-dropdown-item p-ripple&quot;]/div[@class=&quot;flex align-items-center gap-2 label-custom ng-star-inserted&quot;]/div[1]</value>
      <webElementGuid>45c11e74-56ac-4177-b009-33dbb17271cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/div[2]/ca-actual-income/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[29]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/div[3]/div[2]/ul/p-dropdownitem[2]/li/div/div</value>
      <webElementGuid>e43d5c09-4248-4d19-ab83-e9a02594aae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[2]/li/div/div</value>
      <webElementGuid>17c8c138-9d66-459d-9a01-40b332df70c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cho thuê/khai thác tài sản' or . = 'Cho thuê/khai thác tài sản')]</value>
      <webElementGuid>b8008c39-2b09-430d-9967-c356ae8a46a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
