<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thu</name>
   <tag></tag>
   <elementGuidId>263e018a-96c7-4cd0-9f0e-e672d4f2fd28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/div[2]/ca-actual-income/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[34]/bpm-formly-group/bpm-formly-field[9]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/div[3]/div[2]/ul/p-dropdownitem[2]/li/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ade3e4ab-c83d-4583-9298-6806d32959b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex align-items-center gap-2 label-custom ng-star-inserted</value>
      <webElementGuid>b0424378-0ffd-4cc6-96f9-2d7d341c8b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thuê để ở</value>
      <webElementGuid>691c80cc-212a-43fb-8ae0-3e90e741d99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-invalid&quot;]/form[@class=&quot;ng-touched ng-dirty ng-invalid&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active approval-tab-error&quot;]/ca-income-source-information[@class=&quot;ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;card card-border ng-star-inserted&quot;]/div[@class=&quot;bord rounded pb-4 mb-4 ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;collapse in show ng-star-inserted&quot;]/ca-actual-income[@class=&quot;ng-touched ng-dirty ng-invalid ng-star-inserted&quot;]/div[@class=&quot;bpm-dynamic-form&quot;]/bpm-formly-form[1]/bpm-formly-field[1]/bpm-formly-group[@class=&quot;ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;ng-star-inserted&quot;]/bpm-formly-group[@class=&quot;col-md-12 row ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;col-md-6&quot;]/bpm-formly-group[@class=&quot;field-group-block ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;col-md-6 ng-star-inserted&quot;]/ca-filter-status-dropdown[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;custom-form&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-xl-8 col-md-7&quot;]/div[@class=&quot;p-inputgroup _input-left&quot;]/div[@class=&quot;input-group-prepend&quot;]/p-dropdown[@class=&quot;dropdown-custom ng-tns-c358-155 ng-untouched ng-pristine ng-invalid ng-star-inserted p-inputwrapper-focus&quot;]/div[@class=&quot;ng-tns-c358-155 p-dropdown p-component p-dropdown-open p-dropdown-clearable&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c358-155 panel-filter p-dropdown-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-items-wrapper ng-tns-c358-155&quot;]/ul[@class=&quot;p-dropdown-items ng-tns-c358-155&quot;]/p-dropdownitem[@class=&quot;ng-tns-c358-155 ng-star-inserted&quot;]/li[@class=&quot;p-dropdown-item p-ripple&quot;]/div[@class=&quot;flex align-items-center gap-2 label-custom ng-star-inserted&quot;]</value>
      <webElementGuid>6153765c-521b-4323-ac78-5febbf80985f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/div[2]/ca-actual-income/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[34]/bpm-formly-group/bpm-formly-field[9]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/div[3]/div[2]/ul/p-dropdownitem[2]/li/div</value>
      <webElementGuid>8fcdc70b-86c1-4485-8cc8-e676fd56bc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[2]/li/div</value>
      <webElementGuid>c6cffb43-f1bd-4341-85a6-2394535bc60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thuê để ở' or . = 'Thuê để ở')]</value>
      <webElementGuid>ffb8be9c-0afc-4ac9-9280-35cfac06a660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
