<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_p-checkbox-box_1_2</name>
   <tag></tag>
   <elementGuidId>158913bc-2d94-4f7e-85bb-ca2b810e9d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab/ca-cic-search-table/p-table/div/div/table/thead/tr/th/p-checkbox/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.text-center.checkbox-header.ng-star-inserted > p-checkbox.mr-2.ng-untouched.ng-pristine.ng-valid > div.p-checkbox.p-component > div.p-checkbox-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf855cfa-1ba0-440d-b9c3-16a4329c8c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-box</value>
      <webElementGuid>65be9bf6-c2c1-4be9-bf94-970cd8f48166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>08a47bb0-ba12-4bf5-a3ef-5f150c0db4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed bosbo p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;ng-tns-c313-159 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c313-159 p-dialog-mask p-component-overlay p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c313-159 p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c313-159&quot;]/ca-cic-searching-dialog[@class=&quot;ng-star-inserted&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active&quot;]/ca-cic-search-table[1]/p-table[@class=&quot;p-none-background&quot;]/div[@class=&quot;p-datatable p-component p-datatable-hoverable-rows&quot;]/div[@class=&quot;p-datatable-wrapper ng-star-inserted&quot;]/table[1]/thead[@class=&quot;p-datatable-thead&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/th[@class=&quot;text-center checkbox-header ng-star-inserted&quot;]/p-checkbox[@class=&quot;mr-2 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;p-checkbox p-component&quot;]/div[@class=&quot;p-checkbox-box&quot;]</value>
      <webElementGuid>bd90a243-87ac-446b-9e27-724c511b19b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab/ca-cic-search-table/p-table/div/div/table/thead/tr/th/p-checkbox/div/div[2]</value>
      <webElementGuid>8300b7ef-5be2-40bb-9681-fee43b26982a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/p-checkbox/div/div[2]</value>
      <webElementGuid>3622ac83-e3b0-4d8e-94c9-caba304769db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
