<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_p-radiobutton-box</name>
   <tag></tag>
   <elementGuidId>b42c6ed4-a290-4962-ae63-e77059ae280d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/ca-header-box/div/div[2]/p-radiobutton[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>abfbe8c4-1d19-4ada-81d8-925e1585b19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>bfd9c08a-c453-4a4f-a71a-bb477bb46b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-box</value>
      <webElementGuid>92405b29-56ab-4270-9e0e-4dc4d49296c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-valid&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active&quot;]/ca-income-source-information[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;card card-border ng-star-inserted&quot;]/div[@class=&quot;bord rounded pb-4 mb-4 ng-untouched ng-pristine ng-valid&quot;]/ca-header-box[1]/div[@class=&quot;d-flex p-3 align-items-center flex-wrap&quot;]/div[@class=&quot;d-flex flex-1 align-items-center&quot;]/p-radiobutton[@class=&quot;pl-4 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;p-radiobutton p-component&quot;]/div[@class=&quot;p-radiobutton-box&quot;]</value>
      <webElementGuid>1902a7c3-1733-4c71-a788-41bc7e4cd660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/ca-header-box/div/div[2]/p-radiobutton[2]/div/div[2]</value>
      <webElementGuid>9a448273-5f3d-4edd-bb0d-ed5c309a4f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-radiobutton[2]/div/div[2]</value>
      <webElementGuid>6357e3e5-7e50-42ca-a5f8-93b7e814aaa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
