<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ang x l</name>
   <tag></tag>
   <elementGuidId>6d085b55-8a4f-420f-8bee-a230b94730e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//as-split-area[@id='main-left']/div/app-common-layout/ngx-spinner/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.overlay.ng-tns-c64-4.ng-trigger.ng-trigger-fadeIn.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d789054e-a655-4d3c-b223-d1de7996de0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay ng-tns-c64-4 ng-trigger ng-trigger-fadeIn ng-star-inserted</value>
      <webElementGuid>b58f4d52-e524-4ff0-b80c-55a48ac84a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đang xử lý...</value>
      <webElementGuid>6267489e-0c29-4808-8da1-4ce507e475e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-left&quot;)/div[@class=&quot;main-app-shell ng-star-inserted&quot;]/app-common-layout[1]/ngx-spinner[@class=&quot;ng-tns-c64-4 ng-star-inserted&quot;]/div[@class=&quot;overlay ng-tns-c64-4 ng-trigger ng-trigger-fadeIn ng-star-inserted&quot;]</value>
      <webElementGuid>8ef4d5a9-f0d4-4f73-b47e-5fb43fafcfce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//as-split-area[@id='main-left']/div/app-common-layout/ngx-spinner/div</value>
      <webElementGuid>0988c161-489d-4a85-83b1-255856ce0031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngx-spinner/div</value>
      <webElementGuid>6123ec6f-536c-488f-8304-a39fa7fcb646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Đang xử lý...' or . = 'Đang xử lý...')]</value>
      <webElementGuid>88ddd9c5-e226-4cfe-8e40-f95c879fb0d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
