<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-msb-save-fill fs-i my-0</name>
   <tag></tag>
   <elementGuidId>96b6d737-cb93-4d86-be4b-023bca67ebab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[7]/div/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-msb-save-fill.fs-i.my-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>44f0a606-a32a-48f2-b1bc-3b5441f4ceea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-msb-save-fill fs-i my-0</value>
      <webElementGuid>737d91ea-771b-4e68-9d77-4a79fbf33502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-valid&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active&quot;]/ca-customer-and-relation-person[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body _custom-body px-0 collapse in show&quot;]/div[@class=&quot;body-content&quot;]/p-table[@class=&quot;p-none-border scroll-y-only table-edit-mode&quot;]/div[@class=&quot;p-datatable p-component p-datatable-scrollable&quot;]/div[@class=&quot;p-datatable-scrollable-wrapper ng-star-inserted&quot;]/div[@class=&quot;p-datatable-scrollable-view&quot;]/div[@class=&quot;p-datatable-scrollable-body ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;row-highlight-blue ng-star-inserted&quot;]/td[@class=&quot;text-center w-140 ng-star-inserted&quot;]/div[@class=&quot;toolbar-action-table d-flex align-items-center justify-content-center gap-2 ng-star-inserted&quot;]/button[@class=&quot;btn btn-toolbar-table&quot;]/i[@class=&quot;icon-msb-save-fill fs-i my-0&quot;]</value>
      <webElementGuid>373ad016-5aff-4beb-b587-fb24973d4a70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[7]/div/button[2]/i</value>
      <webElementGuid>668199cf-974e-495e-ac12-2892783acb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/div/button[2]/i</value>
      <webElementGuid>5127ea14-ca4b-4a0e-8fa3-a36a14636268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
