<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputformly_31_input_phoneNumber_2</name>
   <tag></tag>
   <elementGuidId>0bf09006-0167-4b5d-a88c-7fa72d5077d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formly_31_input_phoneNumber_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formly_31_input_phoneNumber_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb391843-6814-414a-8a12-3e07add4afef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-inputtext p-component ng-untouched ng-valid p-filled ng-dirty</value>
      <webElementGuid>6802dddc-5f01-4bde-9808-fd3808922443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>9e23e75e-6c67-45b7-b296-83a2f44295dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aab0f6db-49de-4177-819e-b615af5e7679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>26645a08-c827-40dd-b0f4-4255e6061d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>bd9e1d95-e6f5-4bda-9135-84906d9a0e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formly_31_input_phoneNumber_2</value>
      <webElementGuid>36577417-adf1-4a4f-a5e1-9105b6d9b89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>52dd0c04-0881-4144-aea2-b06c86ac23eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Số điện thoại</value>
      <webElementGuid>cdecebb2-e387-42a0-9f07-25df58639827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formly_31_input_phoneNumber_2&quot;)</value>
      <webElementGuid>d54931c3-e0c5-4433-85e0-37a1c8803b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formly_31_input_phoneNumber_2']</value>
      <webElementGuid>18a789ef-9435-41cb-a79e-e862c9b3a613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div[3]/div/div/div/div/ca-application-contact/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[3]/formly-wrapper-ui-form-field/div/div/bpm-formly-field-ui-input/input</value>
      <webElementGuid>a32b3866-b22c-4717-bd00-32d5e11a63ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ca-application-contact/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[3]/formly-wrapper-ui-form-field/div/div/bpm-formly-field-ui-input/input</value>
      <webElementGuid>d5383159-dacd-435f-90c7-ef585c64fda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formly_31_input_phoneNumber_2' and @placeholder = 'Số điện thoại']</value>
      <webElementGuid>c16154d2-356f-42cd-b11f-9ce14ca6432a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
