<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_p-inputnumber-input p-inputtext p-component</name>
   <tag></tag>
   <elementGuidId>de244e8a-f772-4fe1-a1c5-005344eeafb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/div[2]/ca-actual-income/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[30]/formly-wrapper-ui-form-field/div/div/ca-bpm-inputnumber-group/div/p-inputnumber/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p-inputnumber.ng-untouched.ng-pristine.ng-invalid.p-inputwrapper-focus > span.p-inputnumber.p-component > input.p-inputnumber-input.p-inputtext.p-component</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>861e1e34-bf92-40e1-9f6d-16ae6b4b60ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>p-inputnumber-input</value>
      <webElementGuid>5daa0bf9-7ce0-4feb-8d05-4c7da41b57b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000.000</value>
      <webElementGuid>5f1ab986-6e91-4337-94bf-fab233ed3482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>664d1822-f5a4-4380-99cc-ae92af3a0814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputnumber-input p-inputtext p-component</value>
      <webElementGuid>bf06b454-52f6-4767-bd72-8065dafac522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-invalid&quot;]/form[@class=&quot;ng-touched ng-dirty ng-invalid&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active approval-tab-error&quot;]/ca-income-source-information[@class=&quot;ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;card card-border ng-star-inserted&quot;]/div[@class=&quot;bord rounded pb-4 mb-4 ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;collapse in show ng-star-inserted&quot;]/ca-actual-income[@class=&quot;ng-touched ng-dirty ng-invalid ng-star-inserted&quot;]/div[@class=&quot;bpm-dynamic-form&quot;]/bpm-formly-form[1]/bpm-formly-field[1]/bpm-formly-group[@class=&quot;ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;ng-star-inserted&quot;]/bpm-formly-group[@class=&quot;col-md-12 row ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;col-md-6 ng-star-inserted&quot;]/formly-wrapper-ui-form-field[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-7 col-xl-8&quot;]/ca-bpm-inputnumber-group[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-inputgroup&quot;]/p-inputnumber[@class=&quot;ng-untouched ng-pristine ng-invalid p-inputwrapper-focus&quot;]/span[@class=&quot;p-inputnumber p-component&quot;]/input[@class=&quot;p-inputnumber-input p-inputtext p-component&quot;]</value>
      <webElementGuid>44dd501b-e3f0-4758-b576-0ea5915cd9d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/div[2]/ca-actual-income/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[30]/formly-wrapper-ui-form-field/div/div/ca-bpm-inputnumber-group/div/p-inputnumber/span/input</value>
      <webElementGuid>f32c2272-bdff-4762-b38f-002c22c769bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ca-bpm-inputnumber-group/div/p-inputnumber/span/input</value>
      <webElementGuid>2521020f-68ca-482e-a161-697cffa23ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '000.000']</value>
      <webElementGuid>97d926b4-594e-4463-b127-110e7b81757b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
