<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputformly_35_input_phoneNumber_2</name>
   <tag></tag>
   <elementGuidId>d41ec438-ec79-48a1-950d-8b5f9218653a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formly_35_input_phoneNumber_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formly_35_input_phoneNumber_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>061bb5a4-b990-41f5-bb88-a9c6aea4e800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-inputtext p-component ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6929921e-7d64-41da-a3dd-c465e44c8653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>1bd0ce6d-9758-45bb-a271-2cc3ebdacb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49850aec-ee95-4f3f-b5f6-676a87431956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>967051e0-cc65-4c0a-b75c-419b26ed2a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2da3b940-f0d9-4126-986a-f32b2d0743a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formly_35_input_phoneNumber_2</value>
      <webElementGuid>c13f2e7c-600e-43a8-beab-1bd7db02b930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>66f62df2-d1a0-4312-bf8b-de3c9873af84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Số điện thoại</value>
      <webElementGuid>86bd8312-35ab-4a79-91d4-abbe02e6493d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formly_35_input_phoneNumber_2&quot;)</value>
      <webElementGuid>033916dd-1414-41ff-b391-72978c6f0296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formly_35_input_phoneNumber_2']</value>
      <webElementGuid>6e3d6960-4558-46e9-954f-6508d11989bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div[3]/div/div/div/div[2]/ca-application-contact/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[3]/formly-wrapper-ui-form-field/div/div/bpm-formly-field-ui-input/input</value>
      <webElementGuid>50b9ede5-9667-447f-be7d-f460960b3f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ca-application-contact/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[3]/formly-wrapper-ui-form-field/div/div/bpm-formly-field-ui-input/input</value>
      <webElementGuid>957a9cd9-811e-4fcf-9631-f7d6fb8acf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formly_35_input_phoneNumber_2' and @placeholder = 'Số điện thoại']</value>
      <webElementGuid>707dfdca-87f3-4e4c-a964-7ca1cf8dd57e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
