<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputformly_31_input_fullName_1</name>
   <tag></tag>
   <elementGuidId>bd70cae9-65e7-4adc-9bca-48430231c75e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formly_31_input_fullName_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formly_31_input_fullName_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bb93d15-65fd-4133-ba4f-9d83edb0dd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-inputtext p-component ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>18ed8ce3-318d-4f6b-9be5-323623238c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>721e5e1b-cfe8-4e3b-83b7-3977baff9421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc324f5b-f66f-4f2d-b774-4db020b0f96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>22114e80-c197-4f0d-a280-8060a8f7e952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c15d0c29-5937-4b40-8781-fb72a15a1c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formly_31_input_fullName_1</value>
      <webElementGuid>7a6579d9-7b1b-4b02-94eb-df8e2648f607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c9bbba1a-1cc4-4a92-8bf3-92d1935d55e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Họ và tên</value>
      <webElementGuid>926d6987-7b85-4703-8387-60b2922a0cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formly_31_input_fullName_1&quot;)</value>
      <webElementGuid>e69525fe-9b39-4a32-b516-add4cdfbac85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formly_31_input_fullName_1']</value>
      <webElementGuid>f591d7fa-9dba-4d72-8c79-e58dc958ae56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div[3]/div/div/div/div/ca-application-contact/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[2]/formly-wrapper-ui-form-field/div/div/bpm-formly-field-ui-input/input</value>
      <webElementGuid>86ce0274-8988-49d8-a278-f46336a404d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ca-application-contact/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[2]/formly-wrapper-ui-form-field/div/div/bpm-formly-field-ui-input/input</value>
      <webElementGuid>50ca19f8-d39c-4483-8637-4bef791ef4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formly_31_input_fullName_1' and @placeholder = 'Họ và tên']</value>
      <webElementGuid>f3c151ec-c6b6-497a-8bef-4e749c438368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
