<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_addressLine</name>
   <tag></tag>
   <elementGuidId>04110d9e-7259-4f10-82d5-9c15b39ead74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='addressLine']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;addressLine&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af4b6849-6394-4255-bd8d-c21ffc826e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid p-inputtext p-component ng-star-inserted</value>
      <webElementGuid>e4066eda-0087-4780-9e8c-6645990c6361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressLine</value>
      <webElementGuid>c6b4f1f8-9b38-4bf9-8a2c-e785ec350970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>addressLine</value>
      <webElementGuid>e0f1774c-136f-4d4e-8ec8-b2dcbb254f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập số nhà/ tên đường...</value>
      <webElementGuid>cee916ca-444e-48d9-8e60-080945bc8601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>bd871af8-951f-4ab3-9c81-2099eec2f4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>a944f9ee-334d-48d0-b92f-38cfb9862ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-valid&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active&quot;]/ca-customer-and-relation-person[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body _custom-body px-0 collapse in show&quot;]/div[@class=&quot;body-content&quot;]/p-table[@class=&quot;p-none-border scroll-y-only table-edit-mode&quot;]/div[@class=&quot;p-datatable p-component p-datatable-scrollable&quot;]/div[@class=&quot;p-datatable-scrollable-wrapper ng-star-inserted&quot;]/div[@class=&quot;p-datatable-scrollable-view&quot;]/div[@class=&quot;p-datatable-scrollable-body ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;row-highlight-blue ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid p-inputtext p-component ng-star-inserted&quot;]</value>
      <webElementGuid>1b7532f0-63cb-4934-9abd-9634829dc5eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='addressLine']</value>
      <webElementGuid>8b0a715f-e34e-4de2-844c-4c24269b1163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[6]/input</value>
      <webElementGuid>910f27ef-4de3-40fb-8aa2-e7b72d3ac02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>1f31bdb1-f4c3-4c63-b990-b9a14eec3f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'addressLine' and @placeholder = 'Nhập số nhà/ tên đường...']</value>
      <webElementGuid>b0f2a48e-38d3-4727-a728-b22c72ec031c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
