<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputformly_12_input_partnerCode_8</name>
   <tag></tag>
   <elementGuidId>8a566b61-cde3-40ae-8980-4e9041a385f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formly_12_input_partnerCode_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formly_12_input_partnerCode_8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28f525a3-d092-4248-8d49-37137d46457d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-inputtext p-component ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d5c3e944-6aea-43ad-a80e-880271802cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>77ddae8c-72cc-44e1-b544-582ed3d372ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32d4b466-8fa2-4f58-9291-f5ddf674588e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>4e78b727-15b3-4b7c-9bcd-c9220cbba706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>bed34f50-ff22-4f3c-9d16-631a2899434d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formly_12_input_partnerCode_8</value>
      <webElementGuid>3e99edee-481a-49ea-a2b4-3bbdc055a6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7c770032-270b-411c-b5e2-f275bb43bdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập mã đối tác</value>
      <webElementGuid>148793d0-8961-44a8-91fa-c2beb5ad8d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formly_12_input_partnerCode_8&quot;)</value>
      <webElementGuid>e43f6329-6af4-4cd8-abf9-2270ffc69737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formly_12_input_partnerCode_8']</value>
      <webElementGuid>9865e62b-e12b-4bc5-a44d-ba046ba6aaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab/ca-init-application-info/div/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[9]/formly-wrapper-ui-form-field/div/div/bpm-formly-field-ui-input/input</value>
      <webElementGuid>247e272b-2c6d-4824-bc3f-58a0eda6ccb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bpm-formly-field[9]/formly-wrapper-ui-form-field/div/div/bpm-formly-field-ui-input/input</value>
      <webElementGuid>914480cf-cefd-443a-a9fa-a8edd7b19fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formly_12_input_partnerCode_8' and @placeholder = 'Nhập mã đối tác']</value>
      <webElementGuid>35116b3d-68ae-4e8b-b20d-609d2b33ce9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
