<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Chn thnh ph</name>
   <tag></tag>
   <elementGuidId>e6d7393b-7be0-461b-93fd-f00e3bce72f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[3]/p-dropdown/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c358-100.p-dropdown-label.p-inputtext.p-placeholder.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e411972-ab2d-4451-b143-d6fc06a4c29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c358-100 p-dropdown-label p-inputtext p-placeholder ng-star-inserted</value>
      <webElementGuid>92129caf-c7fd-47f8-a8e7-b1d563638116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>33ca02e0-1ccc-47e3-b797-6ee9f936a2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn thành phố</value>
      <webElementGuid>72a7db03-36e9-427e-9fa4-bd64fe2416fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane approval-tab-error active&quot;]/ca-customer-and-relation-person[@class=&quot;ng-touched ng-invalid ng-dirty&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body _custom-body px-0 collapse in show&quot;]/div[@class=&quot;body-content&quot;]/p-table[@class=&quot;p-none-border scroll-y-only table-edit-mode&quot;]/div[@class=&quot;p-datatable p-component p-datatable-scrollable&quot;]/div[@class=&quot;p-datatable-scrollable-wrapper ng-star-inserted&quot;]/div[@class=&quot;p-datatable-scrollable-view&quot;]/div[@class=&quot;p-datatable-scrollable-body ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;row-highlight-blue ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/p-dropdown[@class=&quot;ng-tns-c358-100 ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c358-100 p-dropdown p-component p-dropdown-clearable&quot;]/span[@class=&quot;ng-tns-c358-100 p-dropdown-label p-inputtext p-placeholder ng-star-inserted&quot;]</value>
      <webElementGuid>f9bf9b71-ba39-4f56-805a-2b79a7c759f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[3]/p-dropdown/div/span</value>
      <webElementGuid>8587bcaa-985c-472d-ae9b-b37d70d9c3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/p-dropdown/div/span</value>
      <webElementGuid>b0d52d0d-021e-4de2-b2b1-ab5b3726ef2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Chọn thành phố' or . = 'Chọn thành phố')]</value>
      <webElementGuid>31629143-67bb-4a89-8f27-b4cb183c762f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
