<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ngi hn phi khng bo lnh tr n</name>
   <tag></tag>
   <elementGuidId>53ba58e3-fff1-4170-aa5f-8eb67153677c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdownitem[2]/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>69297636-508a-4e2b-b58c-b2ff2ee4d99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>1d964459-ec7e-4d04-b0e7-2682d1f21c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Người hôn phối không bảo lãnh trả nợ</value>
      <webElementGuid>b0471dd1-8579-4925-89eb-c7cf36a0dcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed bosbo&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c358-154 p-dropdown-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-items-wrapper ng-tns-c358-154&quot;]/ul[@class=&quot;p-dropdown-items ng-tns-c358-154&quot;]/p-dropdownitem[@class=&quot;ng-tns-c358-154 ng-star-inserted&quot;]/li[@class=&quot;p-dropdown-item p-ripple&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>499f7f1f-64d6-42db-9495-43ae7f40814a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[2]/li/span</value>
      <webElementGuid>378510d0-6e7c-413e-bab5-f053548a110d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Người hôn phối không bảo lãnh trả nợ' or . = 'Người hôn phối không bảo lãnh trả nợ')]</value>
      <webElementGuid>aa6dd425-d56d-4a94-85de-aba1ea220e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
