<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_p-toast-icon-close-icon pi pi-times ng_d4a75d</name>
   <tag></tag>
   <elementGuidId>0c06c7cd-d2c1-4314-a39a-be6d526fa7cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//as-split-area[@id='main-left']/div/app-common-layout/p-toast[2]/div/p-toastitem/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-toast-icon-close-icon.pi.pi-times.ng-tns-c185-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>24aa6e3e-2638-43c1-9e0d-2ad6448120ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-toast-icon-close-icon pi pi-times ng-tns-c185-8</value>
      <webElementGuid>9966a4ec-b0f1-494e-bd17-3a4dd684be40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-left&quot;)/div[@class=&quot;main-app-shell ng-star-inserted&quot;]/app-common-layout[1]/p-toast[@class=&quot;ng-tns-c186-2 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c186-2 p-toast p-component p-toast-top-right&quot;]/p-toastitem[@class=&quot;ng-tns-c185-8 ng-trigger ng-trigger-toastAnimation ng-tns-c186-2 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c185-8 ng-trigger ng-trigger-messageState p-toast-message-success p-toast-message&quot;]/div[@class=&quot;p-toast-message-content ng-tns-c185-8&quot;]/button[@class=&quot;p-toast-icon-close p-link ng-tns-c185-8 p-ripple ng-star-inserted&quot;]/span[@class=&quot;p-toast-icon-close-icon pi pi-times ng-tns-c185-8&quot;]</value>
      <webElementGuid>25134887-b7bf-4fab-b156-ece0c6778cd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//as-split-area[@id='main-left']/div/app-common-layout/p-toast[2]/div/p-toastitem/div/div/button/span</value>
      <webElementGuid>377634be-ee62-443e-9d8f-088908cac656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span</value>
      <webElementGuid>63b3639f-01bc-4563-a5ac-102c2205beaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
