<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Chn qun huyn</name>
   <tag></tag>
   <elementGuidId>b290c4be-192e-4f1a-a3fc-3b5d3f96387d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[4]/p-dropdown/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c358-101.p-dropdown-label.p-inputtext.p-placeholder.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>08c887e1-8902-4192-a5ea-c2a271bb538f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c358-101 p-dropdown-label p-inputtext p-placeholder ng-star-inserted</value>
      <webElementGuid>499c8cf1-4709-43a9-9c0a-eb5f94dfbf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c9cb652c-7e33-46bb-929f-fe3e1adc75a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn quận huyện</value>
      <webElementGuid>fd1713bb-197d-4bba-8df1-029b1c567950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane approval-tab-error active&quot;]/ca-customer-and-relation-person[@class=&quot;ng-touched ng-invalid ng-dirty&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body _custom-body px-0 collapse in show&quot;]/div[@class=&quot;body-content&quot;]/p-table[@class=&quot;p-none-border scroll-y-only table-edit-mode&quot;]/div[@class=&quot;p-datatable p-component p-datatable-scrollable&quot;]/div[@class=&quot;p-datatable-scrollable-wrapper ng-star-inserted&quot;]/div[@class=&quot;p-datatable-scrollable-view&quot;]/div[@class=&quot;p-datatable-scrollable-body ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;row-highlight-blue ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/p-dropdown[@class=&quot;ng-tns-c358-101 ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c358-101 p-dropdown p-component p-dropdown-clearable&quot;]/span[@class=&quot;ng-tns-c358-101 p-dropdown-label p-inputtext p-placeholder ng-star-inserted&quot;]</value>
      <webElementGuid>4e50e6fd-495b-4d55-8e1e-bf59227aeb87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[4]/p-dropdown/div/span</value>
      <webElementGuid>d64a0f30-de1f-4639-bcef-f2ec3e587cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/p-dropdown/div/span</value>
      <webElementGuid>7b6f1273-462b-40ef-8e63-5fe54cc72233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Chọn quận huyện' or . = 'Chọn quận huyện')]</value>
      <webElementGuid>028dba92-caf6-484e-b585-68f50244820f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
