<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_p-dialog-header-close-icon pi pi-times_7a29d4</name>
   <tag></tag>
   <elementGuidId>4dd6c56d-430c-4e81-a5fa-e978a98186d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-dynamicdialog/div/div/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-dialog-header-close-icon.pi.pi-times.ng-tns-c313-159</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c0b548f-174a-49c3-bbb3-9574481d65b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dialog-header-close-icon pi pi-times ng-tns-c313-159</value>
      <webElementGuid>d862c8c7-f6ff-4eee-8a42-22a3cbddbe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed bosbo&quot;]/p-dynamicdialog[@class=&quot;ng-tns-c313-159 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c313-159 p-dialog-mask p-component-overlay p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c313-159 p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-header ng-tns-c313-159 ng-star-inserted&quot;]/div[@class=&quot;p-dialog-header-icons ng-tns-c313-159&quot;]/button[@class=&quot;ng-tns-c313-159 p-dialog-header-icon p-dialog-header-maximize p-link ng-star-inserted&quot;]/span[@class=&quot;p-dialog-header-close-icon pi pi-times ng-tns-c313-159&quot;]</value>
      <webElementGuid>fcd64c2c-83f2-49ad-a007-dff381a11d8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dynamicdialog/div/div/div/div/button/span</value>
      <webElementGuid>52f653d0-cbfb-4eb0-bf95-1f0a22b8f13f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
