<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_To yu cu</name>
   <tag></tag>
   <elementGuidId>bf2e9aa9-1ec5-479c-a475-60c7ff1a8d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='request-list']/div/div/div[2]/bpm-button/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-button-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2ab9891-0408-4c93-8d9b-980a3d16e4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label</value>
      <webElementGuid>c0757270-c9f6-4ea5-b063-8f60b56b3f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tạo yêu cầu </value>
      <webElementGuid>48e67b39-f9a5-4d74-be7a-2f540248ea2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;request-list&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;p-d-flex p-justify-between p-pb-2&quot;]/div[@class=&quot;_top-right-table&quot;]/bpm-button[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;bpm-border-radius-button bpm-font-size p-button p-component primary&quot;]/span[@class=&quot;p-button-label&quot;]</value>
      <webElementGuid>88c0fabe-b198-4761-8841-62c8ec9677e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='request-list']/div/div/div[2]/bpm-button/button/span</value>
      <webElementGuid>99ef544b-06fb-4578-8342-dd141e2ce2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bpm-button/button/span</value>
      <webElementGuid>df0b8940-4f27-485a-b822-bf614b5ab5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Tạo yêu cầu ' or . = ' Tạo yêu cầu ')]</value>
      <webElementGuid>337c16bc-e782-41cc-8c0a-081b252cf2d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
