<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Chn phng x</name>
   <tag></tag>
   <elementGuidId>ca6b8fcd-62a9-49c4-8e50-104cfd69da27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[5]/p-dropdown/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c358-102.p-dropdown-label.p-inputtext.p-placeholder.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>83925008-a7a3-4947-84bf-5d3ec9181da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c358-102 p-dropdown-label p-inputtext p-placeholder ng-star-inserted</value>
      <webElementGuid>090ec87e-e3f2-4790-8bc4-7361f4c78ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>a010b6c8-6e14-4269-ac40-e7f45ebb390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn phường xã</value>
      <webElementGuid>4e19dd2c-2da2-43e6-8115-5cc6323d264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane approval-tab-error active&quot;]/ca-customer-and-relation-person[@class=&quot;ng-touched ng-invalid ng-dirty&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body _custom-body px-0 collapse in show&quot;]/div[@class=&quot;body-content&quot;]/p-table[@class=&quot;p-none-border scroll-y-only table-edit-mode&quot;]/div[@class=&quot;p-datatable p-component p-datatable-scrollable&quot;]/div[@class=&quot;p-datatable-scrollable-wrapper ng-star-inserted&quot;]/div[@class=&quot;p-datatable-scrollable-view&quot;]/div[@class=&quot;p-datatable-scrollable-body ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;row-highlight-blue ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/p-dropdown[@class=&quot;ng-tns-c358-102 ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c358-102 p-dropdown p-component p-dropdown-clearable&quot;]/span[@class=&quot;ng-tns-c358-102 p-dropdown-label p-inputtext p-placeholder ng-star-inserted&quot;]</value>
      <webElementGuid>27180e4e-8e08-455c-98dd-1f1bcd40e34d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[2]/ca-customer-and-relation-person/div/div/div/p-table[2]/div/div/div/div[2]/table/tbody/tr[2]/td[5]/p-dropdown/div/span</value>
      <webElementGuid>ca0ef812-2201-47a9-9efa-f6f26d914e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/p-dropdown/div/span</value>
      <webElementGuid>e6a95bba-3926-46dd-b933-33a5b0174007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Chọn phường xã' or . = 'Chọn phường xã')]</value>
      <webElementGuid>8c26929e-3bf1-497d-8d1a-e8629dbdec61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
