<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HP</name>
   <tag></tag>
   <elementGuidId>d89628fa-caa1-48f6-908a-6874aabd6a37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab/ca-init-application-info/div/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[7]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c358-22.p-dropdown-label.p-inputtext.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0084f8ae-d767-4732-b560-9932539b5ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c358-22 p-dropdown-label p-inputtext ng-star-inserted</value>
      <webElementGuid>0efd751a-cf8d-4a69-b1bf-90e19b451667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d2a29193-cb5f-4437-8ed3-d11dd491e223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tooltip-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>f746fd4e-e1d7-4b1f-8e0e-63ada613c620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-position-style</name>
      <type>Main</type>
      <value>absolute</value>
      <webElementGuid>3d4ed49d-67de-401a-b5a9-7e115191e616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HP</value>
      <webElementGuid>19d60a44-feba-4120-94c9-d8c115b1ac20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active&quot;]/ca-init-application-info[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/bpm-formly-form[1]/bpm-formly-field[1]/bpm-formly-group[@class=&quot;ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;ng-star-inserted&quot;]/bpm-formly-group[@class=&quot;row ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;col-md-6 ng-star-inserted&quot;]/ca-filter-status-dropdown[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;custom-form&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;p-inputgroup _input-left&quot;]/div[@class=&quot;input-group-prepend&quot;]/p-dropdown[@class=&quot;dropdown-custom ng-tns-c358-22 ng-star-inserted p-inputwrapper-filled ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;ng-tns-c358-22 p-dropdown p-component p-dropdown-clearable&quot;]/span[@class=&quot;ng-tns-c358-22 p-dropdown-label p-inputtext ng-star-inserted&quot;]</value>
      <webElementGuid>ccc2579d-bf26-446c-9939-bce7c1ffcf0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab/ca-init-application-info/div/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[7]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/span</value>
      <webElementGuid>66eced02-d9c0-4bfd-9bba-1e999f3dcb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bpm-formly-field[7]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/span</value>
      <webElementGuid>e73c72f7-9f78-4098-b87b-5b48c2839803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'HP' or . = 'HP')]</value>
      <webElementGuid>a69e5be9-f968-491c-9623-f8cee17710e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
