<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Khc</name>
   <tag></tag>
   <elementGuidId>cc66d02c-5e7f-4fbc-81b2-4f10b4863b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tabset[@id='property-tabs']/div/tab/ca-init-application-info/div/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[7]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c358-22.p-dropdown-label.p-inputtext.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6151286-8a54-4034-ab39-cb0292ef82ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c358-22 p-dropdown-label p-inputtext ng-star-inserted</value>
      <webElementGuid>6d15131c-6db6-4491-ada9-600b214c380f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>4c6267c2-3997-4c2b-b0b3-70b4dfb1ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tooltip-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>5b8b39ef-8f02-479e-930d-2f6fb5580b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-position-style</name>
      <type>Main</type>
      <value>absolute</value>
      <webElementGuid>7e92b90f-5acb-494a-8bef-5a4a6294a0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Khác</value>
      <webElementGuid>b7887a02-c6f7-406b-92de-fa010680ce91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ca-rm-profile-info[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/tabset[@id=&quot;property-tabs&quot;]/div[@class=&quot;tab-content&quot;]/tab[@class=&quot;tab-pane active&quot;]/ca-init-application-info[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/bpm-formly-form[1]/bpm-formly-field[1]/bpm-formly-group[@class=&quot;ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;ng-star-inserted&quot;]/bpm-formly-group[@class=&quot;row ng-star-inserted&quot;]/bpm-formly-field[@class=&quot;col-md-6 ng-star-inserted&quot;]/ca-filter-status-dropdown[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;custom-form&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;p-inputgroup _input-left&quot;]/div[@class=&quot;input-group-prepend&quot;]/p-dropdown[@class=&quot;dropdown-custom ng-tns-c358-22 ng-star-inserted p-inputwrapper-filled ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;ng-tns-c358-22 p-dropdown p-component p-dropdown-clearable&quot;]/span[@class=&quot;ng-tns-c358-22 p-dropdown-label p-inputtext ng-star-inserted&quot;]</value>
      <webElementGuid>789ae27d-42c4-4040-856f-6981de7207cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab/ca-init-application-info/div/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[7]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/span</value>
      <webElementGuid>3fc10072-0990-47eb-ba3e-ae57f500e42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bpm-formly-field[7]/ca-filter-status-dropdown/div/div/div[2]/div/div/p-dropdown/div/span</value>
      <webElementGuid>50fa85a9-8ab3-46be-bf00-aefae228ccb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Khác' or . = 'Khác')]</value>
      <webElementGuid>747e81b4-09a9-4317-aace-5fe0a2b9877c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
