<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaformly_304_inputtextareaautoresize__69b6a7</name>
   <tag></tag>
   <elementGuidId>2e90905a-93f8-4539-83c1-bba629556fb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='formly_304_inputtextareaautoresize_assetAddress_16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formly_304_inputtextareaautoresize_assetAddress_16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d92c6b04-ab77-4007-b555-9fc9f6354f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-textarea min-h-textarea p-inputtextarea p-inputtext p-component p-inputtextarea-resizable ng-untouched p-filled ng-dirty ng-valid</value>
      <webElementGuid>11245e4b-7266-442e-bc6c-4888c4d3187e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2047e12d-bf30-4754-b8ba-1f86a505d842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>8fce7ca9-e119-435b-acaf-c78e4f961c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-auto-resize</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb706b95-fb28-452d-aff4-fc65fd89626a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formly_304_inputtextareaautoresize_assetAddress_16</value>
      <webElementGuid>a818a1eb-03dd-405d-868f-79f45946c50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e9f73dea-b629-4a50-8a3d-fdebb478f07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>a3f9bcd3-d686-49e2-8f44-5e25a00eb194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập địa chỉ/loại xe</value>
      <webElementGuid>cfbeff52-bd29-475a-af44-ae2618b62e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formly_304_inputtextareaautoresize_assetAddress_16&quot;)</value>
      <webElementGuid>00135ad0-de70-451e-b445-b5b3675e2c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='formly_304_inputtextareaautoresize_assetAddress_16']</value>
      <webElementGuid>2f9a04ff-a089-4002-b95a-877e23a2d61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tabset[@id='property-tabs']/div/tab[3]/ca-income-source-information/div/div/div[2]/ca-actual-income/div/bpm-formly-form/bpm-formly-field/bpm-formly-group/bpm-formly-field/bpm-formly-group/bpm-formly-field[31]/bpm-formly-group/bpm-formly-field[17]/formly-wrapper-ui-form-field/div/div/ca-bpm-textarea-autoresize/div/textarea</value>
      <webElementGuid>eeefbf79-5149-4026-ac4b-62e8f22c7872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bpm-formly-field[17]/formly-wrapper-ui-form-field/div/div/ca-bpm-textarea-autoresize/div/textarea</value>
      <webElementGuid>30f2e3e4-e7e5-4137-a8b1-129d2ee090f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'formly_304_inputtextareaautoresize_assetAddress_16' and @placeholder = 'Nhập địa chỉ/loại xe']</value>
      <webElementGuid>032bb992-7c22-40c8-b735-3e8934b2f013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
