<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lưu</name>
   <tag></tag>
   <elementGuidId>1faa01ed-a503-4d70-96b5-313650daef08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//Button[contains(.,'Lưu')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
